# set.add()
# set.remove()
# set.cler()
# set.pop()
collection={1,2,3,4,5,6,7,8}
collection.add(1)
collection.add(3)
print(collection)
collection.remove(6)
print(collection)
#collection.clear()
print(collection)
collection.pop()
print(collection)
